#!/usr/bin/env python3
"""Generate docs/reference/unified-index.md from the normalized skills + graphs.lock + bridges.

Reproducible replacement for the old hand-written (stale) template. Re-run after the
Phase-1 rebuild to refresh graph stats and (later) add a node-level concept index.

Usage: python scripts/build_unified_index.py
"""
import json, re, pathlib
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
LOCK = json.load(open(ROOT / "graphs.lock"))["libraries"]

DOMAIN = {
    "Foundation Layer": ["numpy", "scipy", "pandas"],
    "ML & Optimization": ["scikit-learn", "xgboost", "lightgbm", "optuna"],
    "Quant Tools": ["vectorbt", "backtrader", "ta-lib"],
}
LIB_DOMAIN = {lib: dom for dom, libs in DOMAIN.items() for lib in libs}


def fm_of(path):
    m = re.match(r"^---\n(.*?)\n---", path.read_text(), re.S)
    return yaml.safe_load(m.group(1)) if m else {}


def scan():
    libs = {}
    playbooks = []
    for p in sorted(SKILLS.rglob("SKILL.md")):
        rel = p.relative_to(SKILLS)
        lib = rel.parts[0]
        fm = fm_of(p)
        entry = {"name": fm.get("name", ""), "desc": fm.get("description", ""),
                 "router": len(rel.parts) == 2, "path": str(rel)}
        if lib == "quant-patterns":
            if len(rel.parts) >= 3:
                playbooks.append(entry)
        else:
            libs.setdefault(lib, []).append(entry)
    return libs, playbooks


def main():
    libs, playbooks = scan()
    bridges = []
    bpath = ROOT / "docs" / "reference" / "cross-library-bridges.json"
    if bpath.exists():
        bridges = [b for b in json.load(open(bpath)).get("bridges", []) if b.get("status") == "RESOLVED"]

    L = ["# Unified Index",
         "",
         "> Cross-library map of the quant-kg-lab stack. Generated by "
         "`scripts/build_unified_index.py` from the skills + `graphs.lock`. "
         "A node-level A–Z concept index is added after the Phase-1 graph rebuild "
         "(see `ROADMAP.md`).",
         "",
         "## Domain taxonomy (the overlay on the library-first layout)",
         "",
         "| Domain | Libraries |",
         "|--------|-----------|"]
    for dom, ls in DOMAIN.items():
        L.append(f"| **{dom}** | {', '.join(ls)} |")
    L.append("| **Workflows** | quant-patterns (composable playbooks) |")

    L += ["", "## Libraries", "",
          "| Library | Domain | Nodes · Edges | Skills | Router |",
          "|---------|--------|---------------|--------|--------|"]
    for lib in sorted(libs, key=lambda x: (LIB_DOMAIN.get(x, "z"), x)):
        info = LOCK.get(lib, {})
        n_skills = len([e for e in libs[lib] if not e["router"]])
        has_router = any(e["router"] for e in libs[lib])
        router = f"[`{lib}`](../../skills/{lib}/SKILL.md)" if has_router else "—"
        L.append(f"| {lib} | {LIB_DOMAIN.get(lib,'—')} | {info.get('nodes','?')} · {info.get('edges','?')} "
                 f"| {n_skills} | {router} |")

    L += ["", "## Skills index", ""]
    for lib in sorted(libs, key=lambda x: (LIB_DOMAIN.get(x, "z"), x)):
        L.append(f"### {lib}")
        for e in sorted(libs[lib], key=lambda x: (not x["router"], x["name"])):
            tag = " *(router)*" if e["router"] else ""
            L.append(f"- [`{e['name']}`](../../skills/{e['path']}){tag} — {e['desc']}")
        L.append("")

    L += ["## Workflow playbooks (composable stack)", ""]
    for e in sorted(playbooks, key=lambda x: x["name"]):
        L.append(f"- [`{e['name']}`](../../skills/{e['path']}) — {e['desc']}")

    L += ["", "## Cross-library bridges (resolved to clean nodes)", ""]
    if bridges:
        L += ["| Source | Target | Relation |", "|--------|--------|----------|"]
        for b in bridges:
            L.append(f"| {b.get('source','')} | {b.get('target','')} | {b.get('relation','')} |")
        L.append("")
        L.append("_Generated by `scripts/inject_cross_edges_v2.py`; overlay graph at "
                 "`knowledge_graphs/_cross_library/`. Bridges that only resolve to noise nodes "
                 "today are held back until the Phase-1 rebuild._")
    else:
        L.append("_Run `scripts/inject_cross_edges_v2.py` to populate resolved bridges._")

    out = ROOT / "docs" / "reference" / "unified-index.md"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out} ({len(libs)} libraries, {sum(len(v) for v in libs.values())} skill entries, "
          f"{len(playbooks)} playbooks, {len(bridges)} bridges)")


if __name__ == "__main__":
    main()
