#!/usr/bin/env python3
"""Generate the per-library documentation hubs (Library Index docs).

Writes docs/libraries/index.md (domain taxonomy) and docs/libraries/<lib>/index.md for
each library — a hub that INDEXES the skills + graph provenance + cross-library bridges
(it does not duplicate the per-module SKILL.md files). Generated: do not hand-edit.

Reads: graphs.lock, knowledge_graphs/<lib>/.graphify/graph.json (noise-filtered for god-node
display per docs/specs/GRAPH_SPEC.md §6), skills/<lib>/, docs/reference/cross-library-bridges.json.

Usage: python scripts/build_library_docs.py
"""
import json, re, pathlib, datetime
from collections import Counter
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
LOCK = json.load(open(ROOT / "graphs.lock"))["libraries"]

DOMAIN = {
    "Foundation": ["numpy", "scipy", "pandas", "statsmodels", "polars", "yfinance"],
    "ML & Optimization": ["scikit-learn", "xgboost", "lightgbm", "optuna", "cvxpy", "imbalanced-learn", "catboost"],
    "Quant Tools": ["vectorbt", "backtrader", "ta-lib", "pyportfolioopt", "riskfolio",
                    "alphalens", "pyfolio", "empyrical", "quantstats", "mplfinance", "ta"],
    "Statistical Models": ["arch", "darts"],
    "Explainability": ["shap"],
    "Bayesian Modelling": ["pymc"],
}
LIB_DOMAIN = {lib: dom for dom, libs in DOMAIN.items() for lib in libs}
IMPORT_NAME = {"scikit-learn": "sklearn", "ta-lib": "talib"}
NOISE = ("tests/", "/test", "test_", "asv_bench", "benchmarks/", "bench_", "examples/",
         "r-package", "apps/", "/doc/", "docs/", ".github", "conftest")
DATE = datetime.date.today().isoformat()


def fm_of(path):
    m = re.match(r"^---\n(.*?)\n---", path.read_text(), re.S)
    return yaml.safe_load(m.group(1)) if m else {}


def module_dirs(lib):
    d = SKILLS / lib
    return sorted(p.name for p in d.iterdir() if p.is_dir() and (p / "SKILL.md").exists()) if d.exists() else []


def graph_facts(lib):
    """(nodes, edges, communities, [ (god_label, degree) ]) from the committed graph, noise-filtered."""
    g = ROOT / "knowledge_graphs" / lib / ".graphify" / "graph.json"
    if not g.exists():
        return None
    data = json.load(open(g))
    nodes, links = data.get("nodes", []), data.get("links", data.get("edges", []))
    communities = len({n.get("community") for n in nodes if n.get("community") is not None})
    deg = Counter()
    for l in links:
        deg[l["source"]] += 1; deg[l["target"]] += 1
    def clean(n):
        sf = (n.get("source_file") or "").lower(); lbl = n.get("label") or ""
        return (not any(p in sf for p in NOISE) and n.get("file_type") in (None, "code")
                and lbl and " " not in lbl and not lbl.startswith("__Pyx") and not lbl.startswith("__pyx")
                and len(lbl) <= 40)
    labels = {n["id"]: n["label"] for n in nodes if clean(n)}
    gods = [(labels[i], d) for i, d in deg.most_common() if i in labels][:6]
    return len(nodes), len(links), communities, gods


def bridges_for(lib):
    bp = ROOT / "docs" / "reference" / "cross-library-bridges.json"
    if not bp.exists():
        return []
    out = []
    for b in json.load(open(bp)).get("bridges", []):
        if b.get("status") != "RESOLVED":
            continue
        s, t = b.get("source", ""), b.get("target", "")
        if s.startswith(lib + "::") or t.startswith(lib + "::") or f"{lib}." in b.get("bridge", ""):
            out.append((s, t, b.get("relation", "")))
    return out


def write_library_hub(lib):
    disp = lib
    imp = IMPORT_NAME.get(lib, lib)
    dom = LIB_DOMAIN.get(lib, "—")
    info = LOCK.get(lib, {})
    facts = graph_facts(lib)
    mods = module_dirs(lib)
    L = [f"# {disp} (`{imp}`)", "",
         "<!-- generated by scripts/build_library_docs.py — do not edit; regenerate to update -->", "",
         "**Type**: Library Index", "**Status**: current",
         f"**Library**: {lib}", f"**Domain**: {dom}",
         f"**Source**: {info.get('repo','?')}@{info.get('commit','?')[:12]}"]
    if facts:
        L.append(f"**Graph**: {facts[0]} nodes · {facts[1]} edges")
    L += [f"**Last Verified**: {DATE}", "", "## Overview", "",
          f"Hub for the **{lib}** library ({dom} tier). The per-module API reference lives in the "
          f"skills below; this page indexes them alongside graph provenance and cross-library bridges.", ""]
    # Skills
    L += ["## Skills", "", "| Skill | Module | Covers |", "|-------|--------|--------|"]
    router = SKILLS / lib / "SKILL.md"
    if router.exists():
        rfm = fm_of(router)
        L.append(f"| [`{rfm.get('name', lib)}`](../../../skills/{lib}/SKILL.md) | (router) | "
                 f"{(rfm.get('description','') or '').replace('Use when ','')[:80]} |")
    for mod in mods:
        fm = fm_of(SKILLS / lib / mod / "SKILL.md")
        covers = (fm.get("description", "") or "").split(" — ")[0].split(". ")[0]
        for pfx in ("Use when working with ", "Use when "):
            if covers.startswith(pfx):
                covers = covers[len(pfx):]
        L.append(f"| [`{fm.get('name', lib+'-'+mod)}`](../../../skills/{lib}/{mod}/SKILL.md) | `{imp}.{mod}` | {covers} |")
    # Graph provenance
    if facts:
        gods = ", ".join(f"`{lbl}` ({d})" for lbl, d in facts[3]) or "—"
        L += ["", "## Graph provenance", "",
              f"- **God nodes** (public-API hubs, noise-filtered): {gods}",
              f"- **Communities**: {facts[2]}",
              f"- **Edge audit**: [edge-audit-{lib}.md](../../reference/edge-audits/edge-audit-{lib}.md)",
              f"- **Rebuild**: `scripts/rebuild_graph.sh {lib}`"]
    # Bridges
    br = bridges_for(lib)
    if br:
        L += ["", "## Cross-library bridges", "", "| Source | Target | Relation |", "|--------|--------|----------|"]
        for s, t, rel in br:
            L.append(f"| {s} | {t} | {rel} |")
    L += ["", "## Related", "",
          "- [Libraries index](../index.md) — the domain taxonomy",
          "- [Unified index](../../reference/unified-index.md)", ""]
    out = ROOT / "docs" / "libraries" / lib / "index.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L))


def write_quant_patterns_hub():
    pb = sorted(p.parent.name for p in (SKILLS / "quant-patterns").glob("*/SKILL.md"))
    L = ["# Quant Patterns (workflow playbooks)", "",
         "<!-- generated by scripts/build_library_docs.py — do not edit; regenerate to update -->", "",
         "**Type**: Library Index", "**Status**: current",
         "**Library**: quant-patterns", "**Domain**: Workflows", f"**Last Verified**: {DATE}", "",
         "## Overview", "",
         "Cross-library workflow playbooks — the composable-stack layer. Each composes atomic skills "
         "into an end-to-end research loop.", "", "## Playbooks", "",
         "| Playbook | Covers |", "|----------|--------|"]
    for name in pb:
        fm = fm_of(SKILLS / "quant-patterns" / name / "SKILL.md")
        covers = (fm.get("description", "") or "").replace("Use when ", "").split(" — ")[0].split(". ")[0]
        L.append(f"| [`{fm.get('name', name)}`](../../../skills/quant-patterns/{name}/SKILL.md) | {covers} |")
    L += ["", "## Related", "", "- [Libraries index](../index.md)", ""]
    out = ROOT / "docs" / "libraries" / "quant-patterns" / "index.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L))


def write_domain_index():
    # lock-driven (QKG_018 F5): every graphs.lock library appears; the DOMAIN
    # taxonomy is a mapping with a fallback, never a roster.
    unknown = sorted(set(LOCK) - set(LIB_DOMAIN))
    if unknown:
        print(f"warning: libraries missing from DOMAIN taxonomy (will appear under 'Other'): {unknown}")
    groups = {}
    for lib in LOCK:
        groups.setdefault(LIB_DOMAIN.get(lib, "Other"), []).append(lib)
    L = ["# Libraries — by domain", "",
         "<!-- generated by scripts/build_library_docs.py — do not edit; regenerate to update -->", "",
         "**Type**: Library Index", "**Status**: current", "**Domain**: (index)", f"**Last Verified**: {DATE}", "",
         "Per-library hubs, grouped by tier. Each hub indexes that library's skills, graph provenance, "
         "and cross-library bridges.", ""]
    for dom in sorted(groups):
        L += [f"## {dom}", ""]
        for lib in sorted(groups[dom]):
            info = LOCK.get(lib, {})
            L.append(f"- [{lib}]({lib}/index.md) — {info.get('repo','')}")
        L.append("")
    L += ["## Workflows", "", "- [quant-patterns](quant-patterns/index.md) — cross-library workflow playbooks", ""]
    (ROOT / "docs" / "libraries" / "index.md").write_text("\n".join(L))


def main():
    for lib in LOCK:
        write_library_hub(lib)
    write_quant_patterns_hub()
    write_domain_index()
    n = len(LOCK) + 1
    print(f"wrote docs/libraries/index.md + {n} library hubs")


if __name__ == "__main__":
    main()
