#!/usr/bin/env python3
"""Lint docs/ against docs/_development/standards.md — the docs analog of validate_skills.py.

Checks (gate on --ci):
  1. every hand-written doc has an identity block with a `Type` in the closed enum;
  2. no dangling links — every `](path)` to a repo file/dir resolves;
  3. docs/_development/doc_inventory.yaml matches what is on disk.
Freshness (Last Verified present + ISO) is checked; missing/invalid is an error.

Usage:
  python scripts/doc_audit.py            # report
  python scripts/doc_audit.py --ci       # exit 1 on any error
  python scripts/doc_audit.py --write     # (re)generate doc_inventory.yaml from disk
"""
import sys, re, json, pathlib
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
CENSUS = DOCS / "_development" / "doc_inventory.yaml"
TYPES = ["Spec", "Guide", "Library Index", "ADR", "Audit", "Generated", "Narrative"]
STATUSES = ["current", "draft", "stale", "superseded", "proposed", "accepted"]
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

def skip(path):
    parts = path.relative_to(DOCS).parts
    if parts and parts[0] == "archive":
        return True                                   # historical snapshots
    if path.name.startswith("template-"):
        return True                                   # placeholder templates
    return False

def field(text, key):
    m = re.search(rf"^\*\*{re.escape(key)}\*\*:\s*(.+?)\s*$", text, re.M)
    return m.group(1).strip() if m else None

def check_links(path, text, errors):
    for m in re.finditer(r"\]\(([^)]+)\)", text):
        # skip inline-code examples like `](path)` (backtick on both sides)
        if text[m.start()-1:m.start()] == "`" and text[m.end():m.end()+1] == "`":
            continue
        target = m.group(1).strip()
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        target = target.split("#", 1)[0]
        if not target:
            continue
        resolved = (path.parent / target).resolve()
        if not resolved.exists():
            errors.append(f"dangling link: {target}")

def audit():
    census, errors_by_doc = [], {}
    for path in sorted(DOCS.rglob("*.md")):
        if skip(path):
            continue
        rel = str(path.relative_to(ROOT))
        text = path.read_text()
        errs = []
        generated = "<!-- generated by" in text or path.relative_to(DOCS).parts[0] == "reference"
        if generated:
            dtype = "Generated"
        else:
            dtype = field(text, "Type")
            if dtype not in TYPES:
                errs.append(f"Type missing or not in enum: {dtype!r}")
            status = field(text, "Status")
            if status and status.split(":")[0].strip() not in STATUSES + ["superseded-by"]:
                errs.append(f"Status not valid: {status!r}")
            lv = field(text, "Last Verified")
            if not lv or not DATE_RE.match(lv):
                errs.append(f"Last Verified missing/!ISO: {lv!r}")
        check_links(path, text, errs)
        census.append({"path": rel, "type": dtype,
                       "status": (field(text, "Status") or "generated") if not generated else "generated",
                       "last_verified": field(text, "Last Verified") or ""})
        if errs:
            errors_by_doc[rel] = errs
    return census, errors_by_doc

def load_census():
    if not CENSUS.exists():
        return None
    return yaml.safe_load(CENSUS.read_text()) or {}

def write_census(census):
    payload = {"meta": {"canonical_types": TYPES, "status_values": STATUSES}, "docs": census}
    CENSUS.write_text(yaml.safe_dump(payload, sort_keys=False, width=100))

def main():
    ci = "--ci" in sys.argv
    write = "--write" in sys.argv
    census, errors_by_doc = audit()

    census_err = []
    if write:
        write_census(census)
    else:
        existing = load_census()
        if existing is None:
            census_err.append("doc_inventory.yaml missing — run --write")
        else:
            on_disk = {d["path"]: d["type"] for d in census}
            recorded = {d["path"]: d["type"] for d in existing.get("docs", [])}
            for p in sorted(set(on_disk) - set(recorded)):
                census_err.append(f"doc not in census: {p}")
            for p in sorted(set(recorded) - set(on_disk)):
                census_err.append(f"census lists missing doc: {p}")
            for p in sorted(set(on_disk) & set(recorded)):
                if on_disk[p] != recorded[p]:
                    census_err.append(f"census type drift: {p} ({recorded[p]} → {on_disk[p]})")

    n_link = sum(1 for errs in errors_by_doc.values() for e in errs if e.startswith("dangling"))
    n_id = sum(1 for errs in errors_by_doc.values() for e in errs if not e.startswith("dangling"))
    print("=== doc audit ===")
    for rel, errs in errors_by_doc.items():
        print(f"ERR {rel}")
        for e in errs:
            print(f"     {e}")
    for e in census_err:
        print(f"CENSUS  {e}")
    print(f"\n=== Summary === docs={len(census)}  identity_errors={n_id}  dangling_links={n_link}  census_errors={len(census_err)}")
    (DOCS / "reference").mkdir(parents=True, exist_ok=True)
    json.dump({"errors": errors_by_doc, "census_errors": census_err,
               "totals": {"docs": len(census), "identity": n_id, "links": n_link, "census": len(census_err)}},
              open(DOCS / "reference" / "doc-audit-report.json", "w"), indent=2)

    if ci and (n_id or n_link or census_err):
        sys.exit(1)

if __name__ == "__main__":
    main()
