#!/usr/bin/env python3
"""Inject curated nodes into a graph.json from a manifest (QKG_021 v2).

Public API surfaces that upstream's source cannot yield are pinned in
tools/curated/<lib>.json and injected as CURATED nodes:

  M1  Cython modules (`.pyx` — no tree-sitter grammar), e.g. numpy.random's
      Generator/default_rng re-exports;
  M2  C-only symbols (ufuncs, builtins like arange, dtype, scalar types) —
      no Python `def` exists to extract;
  M3  symbols whose defining .py file is known to the graph but the node was
      not extracted (extraction miss — curated instead of re-extracting).

Each curated node carries a real semantic description and a truthful
source_file (the module where the symbol is bound/re-exported), joined to that
module's node via a CURATED 'contains' link — the `_cross_library` overlay
precedent. The manifest is generated by scripts/api_surface_diff.py
(--manifest) and reviewed before --apply.

Usage:
  python3 scripts/inject_curated_nodes.py <lib> [--dry-run|--apply]
"""
import sys, json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main():
    argv = sys.argv[1:]
    if len(argv) < 1:
        sys.exit(__doc__)
    lib = argv[0]
    apply = "--apply" in argv
    mpath = ROOT / "tools" / "curated" / f"{lib}.json"
    if not mpath.exists():
        sys.exit(f"no curated manifest: {mpath} (generate with "
                 f"scripts/api_surface_diff.py {lib} --manifest)")
    manifest = json.load(open(mpath))
    gpath = ROOT / "knowledge_graphs" / lib / ".graphify" / "graph.json"
    if not gpath.exists():
        sys.exit(f"missing graph: {gpath}")
    g = json.load(open(gpath))
    byid = {n["id"]: n for n in g["nodes"]}
    modnodes = {}
    for n in g["nodes"]:
        sf = n.get("source_file")
        if sf:
            modnodes.setdefault(sf, n)
    added, skipped, unlinked = [], [], []
    links = list(g.get("links", []))
    existing = {(l["source"], l["target"]) for l in links}
    for entry in manifest["symbols"]:
        label = entry["label"]
        nid = "curated_" + label.rstrip("()").lower()
        if nid in byid:
            skipped.append(nid)
            continue
        sf = entry.get("source_file") or "__init__.py"
        mod = modnodes.get(sf)
        community = mod.get("community") if mod else None
        cname = mod.get("community_name") if mod else None
        node = {
            "id": nid,
            "label": label,
            "file_type": "code",
            "source_file": sf,
            "community": community,
            "community_name": cname,
            "description": entry["description"],
        }
        added.append(node)
        byid[nid] = node
        if mod and (mod["id"], nid) not in existing:
            links.append({
                "source": mod["id"], "target": nid,
                "relation": "contains", "confidence": "CURATED",
                "source_file": sf, "weight": 1,
                "_src": mod["id"], "_tgt": nid, "confidence_score": 1,
            })
        elif not mod:
            unlinked.append(label)
    print(f"{lib}: {len(added)} curated nodes to add, {len(skipped)} already present, "
          f"{len(links) - len(g.get('links', []))} contains links "
          f"({len(unlinked)} unlinked: {unlinked[:8]})")
    if not apply:
        print("dry-run: no changes written (use --apply)")
        return
    g["nodes"] = list(byid.values())
    g["links"] = links
    bak = gpath.with_name("graph.json.curated.bak")
    bak.write_text(json.dumps(json.load(open(gpath)), indent=1))
    gpath.write_text(json.dumps(g, indent=1))
    print(f"applied: {gpath} (backup {bak.name})")


if __name__ == "__main__":
    main()
